version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  test:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: ./logs/test_churn_library.log
    mode: w
  main:
    class: logging.FileHandler
    level: INFO
    formatter: simple
    filename: ./logs/churn_library.log
    mode: w
loggers:
  modelLogger:
    level: INFO
    handlers: [main]
  testLogger:
    level: INFO
    handlers: [test]
    propagate: no
root:
  level: DEBUG
  handlers: [main]